FROM golang as build

WORKDIR /app

COPY go.mod ./

COPY go.sum ./

RUN go mod download

COPY . ./

RUN go build -o /go/bin/app


## Depoly
FROM gcr.io/distroless/base-debian10
COPY --from=build /go/bin/app /app

EXPOSE 8080
USER nonroot:nonroot

CMD ["/app"]